"""Render the synthesized **Cutover Plan (run-of-show)** as a .docx deliverable.

Unlike the runbook / design / MOP / deck deliverables — which re-use the engine's own snapshot-reader
writers verbatim — the cutover plan is an AssessHub *synthesis* (``cutover.build_plan``) with no engine
writer behind it, so its document is produced here in the web layer. It deliberately matches the
engine writers' python-docx conventions (Calibri 10.5pt body, navy headings, "Light Grid Accent 1"
tables, fail-soft on a missing library) so a downloaded Cutover Plan reads as one family with the rest
of the deliverable set.

Signature mirrors the engine writers — ``write_cutover_docx(output_path, snap_dict, label)`` — so it
slots into ``deliverables.generate`` exactly like the others.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List

from . import cutover, engine
from .docx_style import GREY as _GREY
from .docx_style import NAVY as _NAVY
from .docx_style import add_table, ink, kv, new_document

# Print-friendly palette (dark ink on white) — mirrors the light-theme gate tokens.
_GATE_INK = {
    cutover.GATE_GO: (0x1A, 0x7F, 0x37),
    cutover.GATE_COND: (0x9A, 0x67, 0x00),
    cutover.GATE_NOGO: (0xCF, 0x22, 0x2E),
}


def write_cutover_docx(output_path: str, snap_dict: Dict[str, Any], label: str) -> None:
    """Write the cutover-plan run-of-show to ``output_path`` as a .docx."""
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt

    # Engine-shared AS-style furniture; imported here (not at module level) because cisco_toolkit
    # only resolves after the `from . import engine` sys.path bootstrap has run.
    from cisco_toolkit.docmeta import add_acceptance, add_document_control

    plan = cutover.build_plan(snap_dict)
    summary = plan["summary"]
    waves: List[Dict[str, Any]] = plan["waves"]

    doc = new_document()

    def table(headers: List[str], rows: List[List[Any]], widths: List[float] | None = None):
        return add_table(doc, headers, rows, widths)

    # ---- title page ----
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    tr = title.add_run("Migration Cutover Plan")
    tr.bold = True
    tr.font.size = Pt(26)
    tr.font.color.rgb = ink(_NAVY)

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sr = sub.add_run(f"Run-of-Show · {label}")
    sr.font.size = Pt(13)
    sr.font.color.rgb = ink(_GREY)

    verdict = doc.add_paragraph()
    verdict.alignment = WD_ALIGN_PARAGRAPH.CENTER
    vr = verdict.add_run(f"Cutover posture: {summary['verdict']}")
    vr.bold = True
    vr.font.size = Pt(16)
    vr.font.color.rgb = ink(_GATE_INK.get(summary["verdict"], _NAVY))

    stamp = doc.add_paragraph()
    stamp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    gen = snap_dict.get("generated_at") or datetime.now().strftime("%Y-%m-%d %H:%M")
    st = stamp.add_run(f"Generated by AssessHub over engine {engine.ENGINE_SCHEMA_VERSION} · snapshot captured {gen}")
    st.font.size = Pt(9)
    st.font.color.rgb = ink(_GREY)

    # ---- document control (AS-style front matter) ----
    add_document_control(
        doc, document="Migration Cutover Plan (Run-of-Show)", label=label,
        engine_version=str(engine.ENGINE_SCHEMA_VERSION),
        generated_at=snap_dict.get("generated_at"),
        audience="The change advisory board and the war-room participants planning and approving "
                 "the migration windows.",
        exclude=("cutover",))

    if not waves:
        doc.add_paragraph("No migration waves were derived from this snapshot.")
        doc.save(output_path)
        return

    # ---- 1. Executive summary ----
    doc.add_heading("1. Executive summary", level=1)
    doc.add_paragraph(summary["statement"])
    table(
        ["Metric", "Value"],
        [
            ["Migration waves", summary["n_waves"]],
            ["Devices in scope", summary["n_devices"]],
            ["Make-before-break (zero outage)", summary["n_make_before_break"]],
            ["Hard-cutover switches (need a window)", summary["n_hard_cutover"]],
            ["Endpoints cut in a window", summary["hard_cutover_endpoints"]],
            ["Estimated total maintenance window", summary["est_window_label"]],
            ["Gate distribution",
             " · ".join(f"{n} {g}" for g, n in summary["gates"].items() if n)],
        ],
        widths=[3.2, 3.3],
    )
    p = doc.add_paragraph()
    p.add_run("Sequencing: ").bold = True
    p.add_run("waves are ordered pilot-first — the safest zero-outage wave proves the cutover method "
              "before the higher-risk hard-cutover waves run. Window figures are first-order planning "
              "estimates to refine against change-control, not commitments.")

    methodology = summary.get("methodology") or []
    if methodology:
        doc.add_heading("Methodology & assumptions", level=2)
        for item in methodology:
            doc.add_paragraph(item, style="List Bullet")

    # ---- 2. Wave sequence overview ----
    doc.add_heading("2. Recommended wave sequence", level=1)
    table(
        ["#", "Wave", "Gate", "Strategy", "Switches", "Endpoints", "Est. window", "Failing checks"],
        [[w["order"], w["group"], w["gate"], w["strategy"], w["n_switches"], w["endpoints"],
          w["est_window_label"], w["n_fail"]] for w in waves],
        widths=[0.4, 1.0, 1.1, 1.4, 0.8, 0.9, 1.0, 0.9],
    )

    # ---- 3. Per-wave run-of-show ----
    doc.add_heading("3. Per-wave run-of-show", level=1)
    for w in waves:
        doc.add_page_break()
        h = doc.add_heading(f"Wave {w['order']} — {w['group']}", level=2)
        for run in h.runs:
            run.font.color.rgb = ink(_GATE_INK.get(w["gate"], _NAVY))

        meta = doc.add_paragraph()
        kv(meta, "Gate:", w["gate"], _GATE_INK.get(w["gate"], _NAVY))
        meta.add_run("    ")
        kv(meta, "Strategy:", w["strategy"])
        meta.add_run("    ")
        kv(meta, "Readiness:", w["readiness"])
        meta2 = doc.add_paragraph()
        kv(meta2, "Switches:", str(w["n_switches"]))
        meta2.add_run("    ")
        kv(meta2, "Endpoints:", str(w["endpoints"]))
        meta2.add_run("    ")
        kv(meta2, "Estimated window:", w["est_window_label"])

        br = w.get("blast_radius")
        if br:
            p = doc.add_paragraph()
            kv(p, "Worst-case blast radius:",
               f"{br['host']} ({br['severity']}) — {br['stranded']} endpoint(s) stranded across "
               f"{br['vlans_impacted']} VLAN(s). {br['detail']}")
        if w.get("keystones"):
            p = doc.add_paragraph()
            kv(p, "Keystone devices in this wave:", ", ".join(w["keystones"]))

        # Gating checks
        gating_rows: List[List[Any]] = [[b["status"].upper(), b["check"], b["phase"], b["note"]]
                                        for b in w.get("blockers", [])]
        for cl in w.get("critical_crosslayer", []):
            gating_rows.append(["CRITICAL", f"{cl['title']} ({cl['layers']})", cl["id"],
                                cl["recommendation"]])
        if gating_rows:
            doc.add_heading("Gating checks — resolve before this wave passes", level=3)
            table(["Status", "Check", "Phase / ID", "Note"], gating_rows,
                  widths=[0.9, 2.0, 1.1, 2.5])

        # Run-of-show steps
        doc.add_heading("Run-of-show", level=3)
        for i, step in enumerate(w["run_of_show"], start=1):
            p = doc.add_paragraph(style="List Number")
            r = p.add_run(f"[{step['phase']}] ")
            r.bold = True
            r.font.color.rgb = ink(_NAVY)
            p.add_run(step["action"])

        # Pre-cutover remediation
        rem = w.get("remediation", [])
        if rem:
            doc.add_heading(f"Pre-cutover remediation ({len(rem)})", level=3)
            table(["Device", "Severity", "Category", "Fix"],
                  [[r["device"], r["severity"], r["category"], r["title"]] for r in rem[:25]],
                  widths=[1.0, 0.9, 1.3, 3.3])
            if len(rem) > 25:
                doc.add_paragraph(f"… {len(rem) - 25} more in the Remediation deliverable.")

        # Post-cutover validation
        val = w.get("validation", [])
        if val:
            doc.add_heading(f"Post-cutover validation ({len(val)})", level=3)
            doc.add_paragraph("Run after the cut; a deviation from the expected baseline is a "
                              "regression to investigate before sign-off.")
            table(["Severity", "Check", "Command", "Expect"],
                  [[v["severity"], v["check"], v["command"], v["expect"]] for v in val[:30]],
                  widths=[0.8, 1.8, 1.6, 2.3])
            if len(val) > 30:
                doc.add_paragraph(f"… {len(val) - 30} more in the Validation-plan section.")

    # ---- closing acceptance gate (AS-style back matter) ----
    add_acceptance(
        doc, scope_note="Acceptance approves the wave sequence and gates as the plan of record; "
                        "each window still requires its own change approval.")

    doc.save(output_path)
