"""AssessHub sample-fleet freshness gate (Plan A / Tier-2 #10).

The class this pins: the bundled demo snapshot froze at 56 of 86 snapshot keys — every
axis shipped after mid-June was simply invisible in the product's first-run experience.
The sample is regenerated by webapp/sample_data/build_sample.py (which drives the REAL
pipeline), and this gate enforces: sample keys ⊇ golden keys. The golden file already
excludes the date-relative sections and never contains opt-in engines, so plain
superset is the exact contract — a new golden-frozen axis that doesn't reach the demo
fails here until the sample is regenerated."""
import json
import pathlib
from copy import deepcopy

ROOT = pathlib.Path(__file__).resolve().parent.parent


def test_sample_freshness_filter_compares_the_pinned_registry_age_without_mutation():
    """Since 2026-09-28 build_sample judges registry health at the demo's evidence date (the golden
    harness's seam and rule), so source_age_days is a pure function of the pin: it is COMPARED, and a
    drift in it is staleness, not noise. (It used to be stripped because it advanced with the wall
    clock.) Neither input is mutated."""
    from webapp.sample_data.build_sample import _strip_volatile

    left = {
        "data_authorities": {
            "eol": {
                "source_age_days": 7.5,
                "source_retrieved_at": "2026-07-30T13:48:46Z",
                "source_fresh": True,
                "authoritative": True,
            }
        }
    }
    right = deepcopy(left)
    right["data_authorities"]["eol"]["source_age_days"] = 7.6
    before_left, before_right = deepcopy(left), deepcopy(right)

    assert _strip_volatile(left) != _strip_volatile(right)
    assert left == before_left
    assert right == before_right
    assert _strip_volatile(left)["data_authorities"]["eol"] == left["data_authorities"]["eol"]


def test_committed_registry_health_is_judged_at_the_demo_evidence_date():
    """The committed demo states every registry's health AT ITS OWN EVIDENCE DATE (build_sample's pinned
    registry clock): each age is exactly the arithmetic from the published retrieval time to that date, and
    every authority is fresh there. A demo regenerated against the wall clock fails this."""
    from datetime import datetime, timezone
    from webapp.sample_data.build_sample import _SAMPLE_COLLECTION_STAMP as stamp

    evidence = datetime(int(stamp[0:4]), int(stamp[4:6]), int(stamp[6:8]), tzinfo=timezone.utc)
    authorities = _sample()["data_authorities"]
    assert authorities, "the demo publishes no data authorities"
    for name, health in authorities.items():
        retrieved = datetime.fromisoformat(health["source_retrieved_at"].replace("Z", "+00:00"))
        age = round((evidence - retrieved).total_seconds() / 86_400, 6)
        assert health["source_age_days"] == age, (name, health["source_age_days"], age)
        assert health["freshness_status"] == "fresh", (name, health["freshness_status"])


def test_committed_collected_at_is_the_demo_evidence_clock():
    """The committed demo states its collection instant as build_sample's pinned evidence clock, byte for byte:
    not the offset of whichever machine last regenerated it (F9: a workstation build wrote +03:00)."""
    from webapp.sample_data.build_sample import _SAMPLE_REGISTRY_CLOCK

    assert _sample()["collected_at"] == _SAMPLE_REGISTRY_CLOCK


def test_committed_source_receipts_are_the_lf_capture_hashes():
    """The committed demo's byte-bound source receipts were taken over its captures' exact LF text, not over
    whatever newline translation the regenerating host applied. A Windows build whose collection writer let text
    mode translate newlines carried CRLF receipt hashes and byte counts in five sections
    (bgp_configured_peer_baseline, etherchannel_operational_evidence, multichassis_lag_domain_baseline,
    multichassis_lag_typed_observations, vtp_extended_evidence; W36). Exact for the BGP baseline's per-host
    receipts, and a class guard over every 64-hex value anywhere in the demo: none is the hash of a CRLF capture.
    Costs one in-memory build_collections(): no pipeline run."""
    import hashlib
    import re

    from webapp.sample_data.build_sample import build_collections

    cols = build_collections()
    lf = {host: {cmd: hashlib.sha256(text.encode("utf-8")).hexdigest() for cmd, text in outs.items()}
          for host, (_plat, outs) in cols.items()}
    crlf = {hashlib.sha256(text.replace("\n", "\r\n").encode("utf-8")).hexdigest()
            for _host, (_plat, outs) in cols.items() for text in outs.values() if "\n" in text}
    sample = _sample()
    checked = 0
    for cov in sample["bgp_configured_peer_baseline"]["coverage"]:
        for command_key, sha_key in (("config_command", "config_sha256"), ("runtime_command", "runtime_sha256")):
            if cov[sha_key]:
                assert cov[sha_key] == lf[cov["switch"]][cov[command_key]], (cov["switch"], cov[command_key])
                checked += 1
    assert checked > len(cols) // 2  # most hosts' running-config at least: the exact half is not inert
    found = set(re.findall(r"[0-9a-f]{64}", json.dumps(sample)))
    assert not found & crlf, sorted(found & crlf)[:5]
    assert found & {sha for per_host in lf.values() for sha in per_host.values()}  # LF receipts are present


def test_sample_freshness_keeps_lifecycle_and_design_sections_and_detects_wording_drift(tmp_path):
    from webapp.sample_data.build_sample import _freshness_drift, _strip_volatile

    fresh = {
        "generated_at": "run-a",
        "collected_at": "2026-08-07T00:00:00",
        "lifecycle_risk": {"note": "authoritative lifecycle wording"},
        "design_nrfu": {"items": [{"description": "CLI proves PID; entitlement is separate"}]},
    }
    committed = deepcopy(fresh)
    committed["generated_at"] = "run-b"
    path = tmp_path / "sample.json"
    path.write_text(json.dumps(committed), encoding="utf-8")
    assert _freshness_drift(fresh, str(path)) == []

    committed["design_nrfu"]["items"][0]["description"] = "stale support claim"
    path.write_text(json.dumps(committed), encoding="utf-8")
    assert _freshness_drift(fresh, str(path)) == ["design_nrfu"]
    filtered = _strip_volatile(fresh)
    assert "lifecycle_risk" in filtered and "design_nrfu" in filtered and "collected_at" in filtered


def test_sample_fleet_carries_every_golden_section():
    sample = json.loads((ROOT / "webapp" / "sample_data" / "sample_fleet.snapshot.json"
                         ).read_text(encoding="utf-8"))
    golden = json.loads((ROOT / "tests" / "golden" / "snapshot.json"
                         ).read_text(encoding="utf-8"))
    missing = sorted(set(golden) - set(sample))
    assert not missing, (
        f"the bundled demo snapshot is STALE — regenerate it "
        f"(python webapp/sample_data/build_sample.py); missing section(s): {missing}")
    # sanity: it is a real multi-device demo, not a stub
    assert len(sample.get("devices") or {}) >= 10


def test_sample_fleet_carries_engine_subfields_the_superset_check_is_blind_to():
    """Post-v3.25.1 SSOT sweep — guard the two drift classes the top-level key-superset check CANNOT catch,
    both of which really froze once (the 2026-07-02 sample missed the 2026-07-03 waves):
      1. `coverage_matrix` — the engine publishes it unconditionally, but it is golden-EXCLUDED (date-relative
         via the blueprint), so `set(golden) - set(sample)` never requires it.
      2. `verdict` on every ACL finding — a SUB-field inside the existing `acl_line_reachability` key, invisible
         to a top-level-key diff.
    and a third of the same sub-field class (3. below, `blind_links` on every `failure_impact` row).
    A stale sample now fails HERE (regenerate build_sample.py), not silently."""
    sample = json.loads((ROOT / "webapp" / "sample_data" / "sample_fleet.snapshot.json"
                         ).read_text(encoding="utf-8"))
    assert "coverage_matrix" in sample, \
        "sample missing the engine-published coverage_matrix block — regenerate build_sample.py"
    acl = (sample.get("acl_line_reachability") or {}).get("findings") or []
    missing = [f.get("citation") for f in acl if "verdict" not in f]
    assert acl and not missing, (
        "ACL findings must all carry the engine's Verdict ADT `verdict` field (stale sample — regenerate "
        f"build_sample.py); offenders: {missing or 'no ACL findings in the demo'}")
    # 3. `blind_links` on every `failure_impact` row — a SUB-field the producer writes on every record (W32), whose
    #    absence the UI projection reads as a row older than the count (its understatable values withheld).
    impact = sample.get("failure_impact") or []
    stale = [r.get("host") if isinstance(r, dict) else r for r in impact
             if not isinstance(r, dict) or "blind_links" not in r]
    assert impact and not stale, (
        "failure_impact rows must all carry the engine's per-row `blind_links` count (stale sample — regenerate "
        f"build_sample.py); offenders: {stale or 'no failure_impact rows in the demo'}")


def _sample():
    return json.loads((ROOT / "webapp" / "sample_data" / "sample_fleet.snapshot.json"
                       ).read_text(encoding="utf-8"))


def _jnorm(obj):
    """JSON-normalise an engine object (tuples->lists, Counter->dict) so it compares fairly
    against the json-round-tripped committed sample."""
    return json.loads(json.dumps(obj))


def test_sample_detector_schema_matches_engine_exactly():
    """TEXT-freshness lock #1 (the class the key-superset check cannot see): PR #396 renamed the
    l2-native-vlan-1 descriptor checks/threshold and the demo kept the OLD texts until #397
    regenerated it by hand. compute_detector_schema() is pure/deterministic/offline, so the demo's
    embedded copy must equal it exactly -- any descriptor wording change now fails here until the
    sample is regenerated (python webapp/sample_data/build_sample.py). Costs ~ms: no pipeline run."""
    from cisco_toolkit.detector_schema import compute_detector_schema
    sample, engine = _sample(), _jnorm(compute_detector_schema())
    smp = {d.get("key"): d for d in (sample.get("detector_schema") or {}).get("detectors", [])}
    eng = {d["key"]: d for d in engine["detectors"]}
    drifted = sorted(set(smp) ^ set(eng)) + [k for k in sorted(set(smp) & set(eng)) if smp[k] != eng[k]]
    assert sample.get("detector_schema") == engine, (
        f"demo detector_schema drifted from the engine (stale sample -- regenerate "
        f"build_sample.py); drifted detector(s): {drifted}")


def test_sample_drift_native_vlan_row_matches_engine_render():
    """TEXT-freshness lock #2 -- the exact PR-#396 drift class: the engine's rendered f-strings
    changed while the demo kept the old wording. Recompute operational_drift from the sample's OWN
    interfaces (via the from_sparse decode SSOT) and require the committed native-VLAN-1 row to
    match the recomputed render field-for-field. In-memory over ~23 devices: no pipeline run.
    (The Coverage/abstention row needs the collection-time capture record and is deliberately not
    recomputed here; build_sample.py --check covers full-snapshot fidelity.)"""
    from cisco_toolkit.analyze import compute_operational_drift
    from cisco_toolkit.model import InterfaceData
    sample = _sample()
    ai = {h: {p: InterfaceData.from_sparse(dict(pd or {}, port=(pd or {}).get("port") or p))
              for p, pd in (ports or {}).items()}
          for h, ports in (sample.get("interfaces") or {}).items()}
    fresh = next((f for f in compute_operational_drift(ai, [])
                  if "Native VLAN 1" in f.get("title", "")), None)
    committed = next((f for f in (sample.get("operational_drift") or [])
                      if "Native VLAN 1" in f.get("title", "")), None)
    assert fresh and committed, (
        "the demo must exercise the native-VLAN-1 drift row (build_sample seeds native-VLAN "
        "hygiene variety) and the engine must reproduce it from the demo's own interfaces")
    for k in ("title", "detail", "remediation", "severity", "devices"):
        assert _jnorm(fresh.get(k)) == committed.get(k), (
            f"demo native-VLAN-1 drift row field {k!r} drifted from the engine render "
            f"(stale sample -- regenerate build_sample.py):\n"
            f"  engine:    {fresh.get(k)!r}\n  committed: {committed.get(k)!r}")


def test_sample_architecture_review_matches_engine_exactly():
    """TEXT-freshness lock #3 -- the third native-VLAN-1 renderer (and ~24 checks besides):
    compute_architecture_review is pure snapshot synthesis (deterministic -- the golden freezes it),
    so recomputing it OVER the committed sample must reproduce the committed section exactly. Any
    archreview wording change (e.g. the L2-3 basis label) now fails here until the sample is
    regenerated. Costs ~100ms: no pipeline run."""
    from cisco_toolkit.archreview import compute_architecture_review
    sample = _sample()
    fresh = _jnorm(compute_architecture_review(sample))
    committed = sample.get("architecture_review")
    f_titles = {c["id"]: c for c in fresh.get("checks", [])}
    c_titles = {c.get("id"): c for c in (committed or {}).get("checks", [])}
    drifted = sorted(set(f_titles) ^ set(c_titles)) + \
        [k for k in sorted(set(f_titles) & set(c_titles)) if f_titles[k] != c_titles[k]]
    assert committed == fresh, (
        f"demo architecture_review drifted from the engine (stale sample -- regenerate "
        f"build_sample.py); drifted check(s): {drifted}")
