/**
 * scale.test.ts — a 300-node and a 1 000-node fleet stay usable (cluster P3D, 2026-09-28).
 *
 * THE FLEETS. Generated by review/synth-fleet.mjs — deterministic, synthetic from the first byte
 * (`syn-*` hosts, RFC 2544 addresses), and ENGINE-SHAPED: the generator builds a campus topology and
 * derives the cable map the way `cisco_toolkit/analyze.py :: compute_cable_map` does (BFS tiers from
 * the core-role seeds, four barycentre sweeps, off-scan neighbours `collected: false`), real edge
 * betweenness over the collected graph, and a punchlist whose evidence refs resolve. The bytes then go
 * through the app's OWN validator and compiler (tools/lib), so what the layout receives here is what it
 * would receive from a real snapshot of that shape — not a fixture built to suit it. The first block
 * below states what the fleets are, so a generator change that made them easy fails loudly.
 *
 * THE BASELINE (brief disc-compiler-any-snapshot §5): computeLayout took 32 ms at 26 devices, 2 765 ms
 * at 300 and 73 924 ms at 1 000, on the main thread. Profiled on the 300 fleet (node --cpu-prof): 95 %
 * in the route stage — `curveClearance` and `pointToSegment`, i.e. every detour candidate measured
 * against EVERY chassis, and every cable's straight route likewise. Hints grow with the links, so that
 * stage was hints × chassis × 48 chords × up to 12 candidates. The crossing count was a second,
 * smaller quadratic (every pair of edges, once per sweep).
 *
 * THE FIX, and what pins it:
 *   - WORK, COUNTED (the rule in vitest.config.ts: no unit test asserts wall-clock time). The same
 *     primitive-operation counter layout.test.ts uses, held to a budget stated in the fleet's own size:
 *       32·S·(N+E)            per ordering pass (S sweeps; each is a sort and an inversion count),
 *       300·(N+E)             the setup, the embedding and every cable's straight-route query,
 *       4 200·H·√(N+E)        per route hint: its detour ladder is measured only against the chassis
 *                             near each candidate curve, and a curve is as long as the drawing, whose
 *                             side grows as the square root of the node count (tiers wrap into square
 *                             blocks, layout.ts TARGET_TIER_ASPECT).
 *     Measured (counted calls): 300 fleet 15 109 824 against 33.2 M; 1 000 fleet 100 237 503 against
 *     273.6 M. The pre-index layout.ts counts 157 395 323 on the 300 fleet — 4.7× over — so the budget
 *     is not decorative: with that file in place this test goes red (and, through the runaway guard,
 *     goes red quickly instead of counting to the end).
 *   - EXACTNESS AT SCALE. The index may only ever skip a chassis that could not change an answer.
 *     layout.test.ts pins the reference sample to its pre-index digests; here every cable of the 300
 *     fleet is re-measured by brute force, with this file's own arithmetic, against every chassis.
 *   - THE UI. Fabric3D lays a large fabric out in slices of counted work (LAYOUT_SLICE_WORK) and builds
 *     no scene until the layout exists; the reference sample still finishes inside the first,
 *     synchronous slice. Both are asserted below, against the real component.
 *   - THE FABRIC LIST. FabricA11yTree opens tiers only while they fit TREE_OPEN_DEVICE_BUDGET, states
 *     the collapsed counts, and type-ahead still reaches a device inside a collapsed tier.
 *
 * LABORATORY FIGURES (this 14-core host, shared with other agents, Node 24; NOT asserted here —
 * `node review/synth-fleet.mjs --devices N --measure --budget-ms X` re-measures them and turns one into
 * an exit code). At 50-85 % host load: computeLayout 26 devices ~10-15 ms; 300 nodes ~120-170 ms (was
 * 3 498 ms before the fix); 1 000 nodes ~0.55-1.2 s (was 37 404 ms). At 100 % load (2026-09-28): 300
 * nodes median 610 ms (min 256), 1 000 nodes median 4 155 ms (min 2 586) — both OVER the budgets.
 * Stated budgets for a QUIET host of this class, for the CAMPUS-shaped synthetic fleets: ≤ 300 ms at
 * 300 and ≤ 2 s at 1 000 for the whole layout. They are UNCONFIRMED: no quiet-host run exists yet. A
 * flatter fleet costs more (a verifier's one-tier clone of the sample's access layer: 448 745 units at
 * 1 000 against the campus fleet's 387 193). The stage never waits on the whole: it slices the layout.
 *
 * IN A REAL BROWSER (Chromium, Intel iGPU via ANGLE/D3D11, the 300 fleet opened through the app's own
 * "Open a snapshot file" control, host at 100 % load, same-session sample-vs-300 comparisons):
 *   - Draw calls: 77 against the 88 budget at the high tier when idle (the sample: 71), 45-47 during an
 *     orbit drag; 1.77 M triangles, 50 programs, 15 of 300 labels shown.
 *   - Orbit, BEFORE the hover fix below (dev build): 107-108 frames in 6 s, p95 367-417 ms, max
 *     800-1 417 ms (the sample, every run at this load: p95 16.8-99.9 ms). CPU profile: FabricLabels.tsx 3.0-3.7 s
 *     inclusive of each 6 s — React re-rendering one label element per device on every change of the
 *     hovered device, fed by the scene's own hover events during the drag. (An earlier report here of
 *     "p95 33.3 ms, one hitch" did not reproduce and is withdrawn.)
 *   - Orbit, AFTER it (Fabric3D drops scene hover while a press is held; pinned below): dev build
 *     268-282 frames, p95 33-50 ms, FabricLabels 0.8-1.1 s inclusive; release build (vite preview)
 *     p95 33-83 ms against the sample's 16.8-100 ms in the same sessions — at this load the two are
 *     not separable from host noise, so no 300-device frame-time claim is made beyond that.
 *   - Remaining, owned elsewhere: FabricLabels' per-frame tick (projection + resolveLabels) and a
 *     full label re-render on any hover change are O(devices); scene/postfx rendering; load-time long
 *     tasks of 200-800 ms (scene and post-chain creation, not the layout, which ran as ~16 slices).
 */
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { act, createElement, Profiler } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeAll, describe, expect, it, vi } from "vitest";

import { bindSourceWith, compileFabric } from "../../tools/lib/compile-model.mjs";
import { validateSnapshot } from "../../tools/lib/validate-snapshot.mjs";
import type { Fabric } from "../core/types";
import { useInvestigation } from "../core/store";
import { flushTurns } from "../test-support/act-turns";
import type { FabricScene, SceneEvent, SceneOptions } from "./contract";
import { Fabric3D, LAYOUT_SLICE_WORK, type Fabric3DProps } from "./Fabric3D";
import { FabricA11yTree, TREE_OPEN_DEVICE_BUDGET } from "./FabricA11yTree";
import { ALL_CHASSIS_KINDS, prepareChassis } from "./geometry/chassis";
import {
  DEFAULT_SWEEPS,
  ROUTE_CLEARANCE,
  ROUTE_CURVE_SAMPLES,
  ROUTE_T_MARGIN,
  computeLayout,
  layoutJob,
  type FabricLayout,
  type Vec3,
} from "./layout";
import { prepareProceduralMaps } from "./materials";
import { SCENE_DETAIL } from "./quality";

declare global {
  // eslint-disable-next-line no-var
  var IS_REACT_ACT_ENVIRONMENT: boolean;
}
globalThis.IS_REACT_ACT_ENVIRONMENT = true;

/* The scene is mocked, as in Fabric3D.test.tsx: what is asserted is WHEN the stage builds it and with
   WHICH layout, never the picture. */
const built = vi.hoisted(
  (): { opts: unknown[]; cb: unknown[]; disposed: number; setData: { devices: unknown; layout: unknown }[] } => ({
    opts: [],
    cb: [],
    disposed: 0,
    setData: [],
  }),
);
vi.mock("./scene", () => ({
  createScene: (_canvas: HTMLCanvasElement, opts: SceneOptions, cb: unknown): FabricScene => {
    built.opts.push(opts);
    built.cb.push(cb);
    const noop = (): void => {};
    return {
      setData: (devices: unknown, _links: unknown, layout: unknown) => {
        built.setData.push({ devices, layout });
      },
      setSelection: noop,
      setHover: noop,
      setHighlight: noop,
      setTrace: noop,
      focusDevice: noop,
      resetCamera: noop,
      setTheme: noop,
      setQuality: noop,
      resize: noop,
      pick: () => null,
      project: () => null,
      stats: () => ({ fps: 60, frameMs: 16, triangles: 0, programs: 0, converged: true }),
      dispose: () => {
        built.disposed += 1;
      },
      ...{ setReducedMotion: noop, acknowledgeSelection: noop, orbitBy: noop, panBy: noop },
    } as unknown as FabricScene;
  },
}));

/* A fleet-sized unit of work is one test, not a split: laying out 1 000 nodes twice (sliced and whole)
   took 174 s on a saturated run of this host, against the 30 s hang detector. Each such test RAISES its
   own limit inline, as a literal source-hygiene.test.ts can read (vitest.config.ts: an override may only
   raise it); none of them asserts a time. */

/* ── the fleets ────────────────────────────────────────────────────────────── */

interface SynthModule {
  synthFleetBytes(o: { devices: number; seed?: number }): Uint8Array;
  roleMix(n: number): { cores: number; wan: number; firewalls: number; dist: number; aps: number; access: number; pods: number; total: number };
}
/* review/*.mjs is outside every tsconfig by declaration (tsconfig.scripts.json), so it is imported by a
   computed specifier and typed here, at the one place it is used. */
const SYNTH_URL = pathToFileURL(resolve(process.cwd(), "review", "synth-fleet.mjs")).href;
const synth = (await import(/* @vite-ignore */ SYNTH_URL)) as SynthModule;

const hashes = {
  sha256Hex: (b: Uint8Array) => createHash("sha256").update(b).digest("hex"),
  sha1Hex: (b: Uint8Array) => createHash("sha1").update(b).digest("hex"),
};
function fleet(n: number): Fabric {
  const bytes = synth.synthFleetBytes({ devices: n, seed: 1 });
  const v = validateSnapshot(bytes);
  if (!v.ok || v.snap === null) throw new Error(`the compiler refused synth-fleet ${n}: ${JSON.stringify(v.errors)}`);
  return compileFabric(v.snap, bindSourceWith(bytes, { source: `synth-fleet-${n}.snapshot.json`, sourceOrigin: "external-file" }, hashes));
}
const F300 = fleet(300);
const F1000 = fleet(1000);
const optsOf = (f: Fabric) => ({ devices: f.devices, links: f.links, tiers: f.tiers });

describe("the synthetic fleets are what they claim to be", () => {
  for (const [n, f] of [
    [300, F300],
    [1000, F1000],
  ] as const) {
    it(`${n}: every node of the cable map is a device, in a realistic role mix`, () => {
      expect(f.devices).toHaveLength(n);
      const mix = synth.roleMix(n);
      const roles = (r: string) => f.devices.filter((d) => d.role === r).length;
      expect(roles("core")).toBe(mix.cores);
      expect(roles("distribution")).toBe(mix.dist);
      expect(roles("access")).toBe(mix.access + mix.pods);
      // Off-scan CDP neighbours, as the engine publishes them: not collected, with a kind.
      const kinds = (k: string) => f.devices.filter((d) => !d.collected && d.kind === k).length;
      expect([kinds("ap"), kinds("router"), kinds("firewall")]).toEqual([mix.aps, mix.wan, mix.firewalls]);
    });

    it(`${n}: is multi-tier, with the engine's hub at tier 0 and a deep access block`, () => {
      const tiers = new Set(f.devices.map((d) => d.tier));
      expect(tiers.size).toBeGreaterThanOrEqual(4);
      expect(f.devices.filter((d) => d.role === "core").every((d) => d.tier === 0)).toBe(true);
      expect(Math.max(...f.tiers.map((t) => t.length))).toBeGreaterThan(n / 2);
      expect(f.tiers.flat().sort()).toEqual(f.devices.map((d) => d.id).sort());
    });

    it(`${n}: carries links, centrality and findings through the real compiler`, () => {
      expect(f.links.length).toBeGreaterThan(1.5 * n);
      expect(f.links.filter((l) => l.betweenness !== null).length).toBeGreaterThan(n);
      expect(f.links.some((l) => l.isBridge === true)).toBe(true);
      expect(f.links.some((l) => l.opStatus === "down")).toBe(true);
      expect(f.findings.length).toBeGreaterThan(n / 10);
      expect(f.findings.every((x) => (x.evidenceRefs?.length ?? 0) > 0)).toBe(true);
      expect(f.meta.source).toBe(`synth-fleet-${n}.snapshot.json`);
    });
  }
});

/* ── work, counted ─────────────────────────────────────────────────────────── */

/** A counted-work overrun, raised mid-run so a quadratic regression is red in seconds, not minutes. */
class RunawayWork extends Error {
  constructor(readonly ops: number) {
    super(`still running after ${ops} primitive operations`);
  }
}
/**
 * Every call into a function-valued own property of Array.prototype, Map.prototype, Set.prototype or
 * Math while `fn` runs — derived by reflection, so a primitive the layout starts using is counted
 * without being listed. The same instrument as layout.test.ts's (kept in step by hand: a test module
 * cannot import another's helpers without running its tests), including its stated blind spot: a loop
 * that calls none of them. Every loop in layout.ts that does work touches Math or a Map per iteration.
 */
function primitiveOps(fn: (count: () => number) => void, runaway = Infinity): number {
  let n = 0;
  let tripped = false;
  const saved: [object, PropertyKey, PropertyDescriptor][] = [];
  try {
    for (const o of [Array.prototype, Map.prototype, Set.prototype, Math] as object[]) {
      for (const key of Reflect.ownKeys(o)) {
        const d = Object.getOwnPropertyDescriptor(o, key);
        if (key === "constructor" || d === undefined || typeof d.value !== "function") continue;
        const f = d.value as (...a: unknown[]) => unknown;
        saved.push([o, key, d]);
        Object.defineProperty(o, key, {
          ...d,
          value: function counted(this: unknown, ...args: unknown[]): unknown {
            n += 1;
            /* Once, on crossing (the restore loop below runs through these same wrappers). A test on
               `n > runaway`, not equality: a budget stated in the fleet's size is not a whole number. */
            if (!tripped && n > runaway) {
              tripped = true;
              throw new RunawayWork(n);
            }
            return f.apply(this, args);
          },
        });
      }
    }
    n = 0;
    fn(() => n);
    return n;
  } finally {
    for (const [o, key, d] of saved) Object.defineProperty(o, key, d);
  }
}

/** The budget, in the fleet's own size (see the header for each term and what it was measured at). */
const scaleBudget = (n: number, e: number, sweeps: number, hints: number): number =>
  32 * sweeps * (n + e) + 300 * (n + e) + 4200 * hints * Math.sqrt(n + e);

describe("the layout's work is near-linear in the fleet, counted", () => {
  for (const [n, f] of [
    [300, F300],
    [1000, F1000],
  ] as const) {
    it(`${n}: stays inside a budget stated in its own size`, { timeout: 600_000 }, () => {
      const N = f.devices.length;
      const E = f.links.length;
      /* Hints are part of the OUTPUT, so the budget cannot be told them in advance. The runaway guard
         is set from an upper bound on them (at most one per placed link), so a regression is red within
         seconds rather than after counting a quadratic to its end; the budget proper is then judged
         against the hint count the counted run itself produced. */
      const sweeps = DEFAULT_SWEEPS;
      let l: FabricLayout | undefined;
      const ops = primitiveOps(() => {
        l = computeLayout(optsOf(f));
      }, scaleBudget(N, E, sweeps, E));
      expect(l!.diagnostics.sweeps).toBe(sweeps);
      const hints = l!.routeHints.length;
      expect(hints, "precondition: the fleet exercises the detour ladder").toBeGreaterThan(N / 2);
      const budget = scaleBudget(N, E, sweeps, hints);
      expect(ops, `${ops} counted operations against a budget of ${Math.round(budget)}`).toBeLessThanOrEqual(budget);
      // The instrument is live on the stage that matters: every placed link is at least queried.
      expect(ops).toBeGreaterThan(10 * E);
    });
  }

  it("300: every indivisible step is charged for the work it does, so a slice's budget means something", { timeout: 600_000 }, () => {
    /* LAYOUT_SLICE_WORK paces the stage by the units each step REPORTS. A stage that does O(N) work
       and reports one unit makes a slice as long as that stage, whatever the budget says — the defect
       this pins: the embedding (step 7-9, plus the chassis index) was charged 1 unit for ~25·(N+E)
       counted calls, and the last cable's detour ladder was charged nothing at all. The rule is checked
       for EVERY step, not for a list of stages: none costs more than OPS_PER_UNIT counted calls per
       unit it reports (so a step that reports nothing does nothing counted — the return itself). The dearest unit measured is one chassis measured
       along a whole curve (ROUTE_CURVE_SAMPLES chords, ~360 counted calls on both fleets); an ordering
       pass costs ~15-30 per unit. The instrument's blind spot applies (a sort is one call), so this
       bounds the charge from below, not the wall-clock cost of a unit. */
    const OPS_PER_UNIT = 1000;
    const offenders: string[] = [];
    let steps = 0;
    primitiveOps((count) => {
      const job = layoutJob(optsOf(F300));
      for (let r: FabricLayout | null = null; r === null; steps += 1) {
        const w0 = job.work;
        const c0 = count();
        r = job.step(1);
        const units = job.work - w0;
        const ops = count() - c0;
        if (ops > OPS_PER_UNIT * units) offenders.push(`step ${steps}: ${units} unit(s) reported for ${ops} counted calls`);
      }
    });
    expect(steps, "precondition: the fleet is laid out in many steps").toBeGreaterThan(F300.links.length / 2);
    expect(offenders).toEqual([]);
  });

  it("known answer: the exhaustive route scan the index replaced is over this budget on the 300 fleet", { timeout: 600_000 }, () => {
    /* The pre-index route stage, reproduced in this file's own arithmetic, counted the same way: each
       hint's FIRST detour candidate alone is measured against every chassis along every chord. Even
       that lower bound of the old cost — the ladder usually ran further — must exceed the budget's
       hint term, or the budget could not see the regression it exists for. */
    const l = computeLayout(optsOf(F300));
    const N = F300.devices.length;
    const perCandidateExhaustive = primitiveOps(() => {
      const h = l.routeHints[0]!;
      const link = F300.links.find((k) => k.id === h.linkId)!;
      exhaustiveCurve(l, at(l.byId.get(link.a)!), h.mid, at(l.byId.get(link.b)!), [link.a, link.b]);
    });
    const unresolved = l.routeHints.filter((h) => h.resolution === "unresolved").length;
    // An unresolved hint ran its whole ladder: 2 directions × ROUTE_DETOUR_STEPS candidates.
    const exhaustiveFloor = perCandidateExhaustive * (l.routeHints.length + unresolved * 11);
    expect(perCandidateExhaustive).toBeGreaterThan(N * ROUTE_CURVE_SAMPLES);
    expect(exhaustiveFloor).toBeGreaterThan(4200 * l.routeHints.length * Math.sqrt(N + F300.links.length));
  });
});

/* ── exactness at scale, by brute force ────────────────────────────────────── */

const at = (n: { x: number; y: number; z: number }): Vec3 => [n.x, n.y, n.z];
function segmentDistance(p: Vec3, a: Vec3, b: Vec3): { d: number; t: number } {
  const ab: Vec3 = [b[0] - a[0], b[1] - a[1], b[2] - a[2]];
  const len2 = ab[0] * ab[0] + ab[1] * ab[1] + ab[2] * ab[2];
  const raw = len2 === 0 ? 0 : ((p[0] - a[0]) * ab[0] + (p[1] - a[1]) * ab[1] + (p[2] - a[2]) * ab[2]) / len2;
  const t = raw < 0 ? 0 : raw > 1 ? 1 : raw;
  const c: Vec3 = [a[0] + ab[0] * t, a[1] + ab[1] * t, a[2] + ab[2] * t];
  return { d: Math.sqrt((p[0] - c[0]) ** 2 + (p[1] - c[1]) ** 2 + (p[2] - c[2]) ** 2), t };
}
/** The published curve's clearance against EVERY chassis but its ends: nearest, and all within the limit. */
function exhaustiveCurve(l: FabricLayout, a: Vec3, c: Vec3, b: Vec3, ends: readonly string[]): { nearest: number; blocked: string[] } {
  const pts: Vec3[] = [];
  for (let i = 0; i <= ROUTE_CURVE_SAMPLES; i += 1) {
    const t = ROUTE_T_MARGIN + ((1 - 2 * ROUTE_T_MARGIN) * i) / ROUTE_CURVE_SAMPLES;
    const u = 1 - t;
    pts.push([
      u * u * a[0] + 2 * u * t * c[0] + t * t * b[0],
      u * u * a[1] + 2 * u * t * c[1] + t * t * b[1],
      u * u * a[2] + 2 * u * t * c[2] + t * t * b[2],
    ]);
  }
  let nearest = Infinity;
  const blocked: string[] = [];
  for (const o of l.nodes) {
    if (ends.includes(o.id)) continue;
    let d = Infinity;
    for (let i = 1; i < pts.length; i += 1) d = Math.min(d, segmentDistance(at(o), pts[i - 1]!, pts[i]!).d);
    nearest = Math.min(nearest, d);
    if (d < ROUTE_CLEARANCE) blocked.push(o.id);
  }
  return { nearest, blocked: blocked.sort() };
}

describe("the chassis index skips nothing that matters: every cable of the 300 fleet, by brute force", () => {
  const l = computeLayout(optsOf(F300));
  const hintOf = new Map(l.routeHints.map((h) => [h.linkId, h]));
  /* A distance that lands within this of the 12-unit limit is decided by the last bits of two different
     formulae; it is reported, not judged. */
  const EPS = 1e-9;

  it("the crossing count it publishes is the pairwise count, recounted edge pair by edge pair", { timeout: 600_000 }, () => {
    // The inversion count replaced a pairwise loop; on a fleet this size the two must still agree.
    const edges: { layer: number; u: number; v: number }[] = [];
    for (const link of F300.links) {
      const a = l.byId.get(link.a);
      const b = l.byId.get(link.b);
      if (!a || !b || Math.abs(a.layer - b.layer) !== 1) continue;
      const [up, down] = a.layer < b.layer ? [a, b] : [b, a];
      edges.push({ layer: up.layer, u: up.rank, v: down.rank });
    }
    let pairwise = 0;
    for (let i = 0; i < edges.length; i += 1) {
      for (let j = i + 1; j < edges.length; j += 1) {
        const e = edges[i]!;
        const g = edges[j]!;
        if (e.layer === g.layer && (e.u - g.u) * (e.v - g.v) < 0) pairwise += 1;
      }
    }
    expect(edges.length).toBeGreaterThan(F300.devices.length);
    expect(l.diagnostics.crossingsFinal).toBe(pairwise);
  });

  it("every cable with NO hint is clear of every chassis on its straight route", { timeout: 600_000 }, () => {
    let judged = 0;
    const lies: string[] = [];
    for (const link of F300.links) {
      const a = l.byId.get(link.a);
      const b = l.byId.get(link.b);
      if (!a || !b || a.id === b.id || hintOf.has(link.id)) continue;
      for (const o of l.nodes) {
        if (o.id === a.id || o.id === b.id) continue;
        const { d, t } = segmentDistance(at(o), at(a), at(b));
        if (t <= ROUTE_T_MARGIN || t >= 1 - ROUTE_T_MARGIN) continue;
        if (d < ROUTE_CLEARANCE - EPS) lies.push(`${link.id} passes ${d.toFixed(3)} from ${o.id} with no hint`);
      }
      judged += 1;
    }
    expect(judged, "precondition: most cables are hint-free and so judged here").toBeGreaterThan(F300.links.length / 3);
    expect(lies).toEqual([]);
  });

  it("every hint names exactly the chassis that block its straight route, and the nearest one", { timeout: 600_000 }, () => {
    const wrong: string[] = [];
    for (const h of l.routeHints) {
      const link = F300.links.find((k) => k.id === h.linkId)!;
      const a = l.byId.get(link.a)!;
      const b = l.byId.get(link.b)!;
      let nearest = Infinity;
      const blocked: string[] = [];
      for (const o of l.nodes) {
        if (o.id === a.id || o.id === b.id) continue;
        const { d, t } = segmentDistance(at(o), at(a), at(b));
        if (t <= ROUTE_T_MARGIN || t >= 1 - ROUTE_T_MARGIN) continue;
        nearest = Math.min(nearest, d);
        if (d < ROUTE_CLEARANCE) blocked.push(o.id);
      }
      if (JSON.stringify(blocked.sort()) !== JSON.stringify(h.blockedBy)) wrong.push(`${h.linkId}: blockers ${h.blockedBy} vs ${blocked}`);
      if (Math.abs((h.clearance ?? NaN) - nearest) > EPS) wrong.push(`${h.linkId}: clearance ${h.clearance} vs ${nearest}`);
    }
    expect(l.routeHints.length).toBeGreaterThan(100);
    expect(wrong).toEqual([]);
  });

  it("every hint's routed clearance is the true nearest chassis to the published curve, over all of them", { timeout: 600_000 }, () => {
    const wrong: string[] = [];
    for (const h of l.routeHints) {
      const link = F300.links.find((k) => k.id === h.linkId)!;
      const { nearest, blocked } = exhaustiveCurve(l, at(l.byId.get(link.a)!), h.mid, at(l.byId.get(link.b)!), [link.a, link.b]);
      if (Math.abs((h.routedClearance ?? NaN) - nearest) > EPS) wrong.push(`${h.linkId}: routed ${h.routedClearance} vs ${nearest}`);
      if (JSON.stringify(blocked) !== JSON.stringify(h.routedBlockedBy)) wrong.push(`${h.linkId}: still-blocked ${h.routedBlockedBy} vs ${blocked}`);
      if ((h.resolution === "cleared") !== (blocked.length === 0)) wrong.push(`${h.linkId}: resolution ${h.resolution} with ${blocked.length} in the way`);
    }
    // Both outcomes occur, so both the widening search (cleared) and the early stop (blocked) ran.
    expect(new Set(l.routeHints.map((h) => h.resolution))).toEqual(new Set(["cleared", "unresolved"]));
    expect(wrong).toEqual([]);
  });
});

/* ── the stage: sliced, and no scene before its layout ─────────────────────── */

describe("the stage lays a large fleet out in slices and never on one long task", () => {
  beforeAll(async () => {
    await prepareProceduralMaps();
    await prepareChassis(ALL_CHASSIS_KINDS, {
      bevelSegments: SCENE_DETAIL.chassisBevelSegments,
      fineDetail: SCENE_DETAIL.chassisFineDetail,
    });
  }, 120_000);

  let root: Root | null = null;
  let host: HTMLElement | null = null;
  afterEach(() => {
    act(() => {
      root?.unmount();
    });
    host?.remove();
    root = null;
    host = null;
    built.opts.length = 0;
    built.cb.length = 0;
    built.disposed = 0;
    built.setData.length = 0;
  });

  it("the reference sample is laid out inside the first, synchronous slice (unchanged behaviour)", async () => {
    const { fabric } = await import("../core/data");
    const job = layoutJob(optsOf(fabric));
    expect(job.step(LAYOUT_SLICE_WORK), "the sample no longer fits one slice").not.toBeNull();
    expect(job.work).toBeLessThan(LAYOUT_SLICE_WORK);
    // And so the stage builds its scene in the mounting commit, as it always has.
    host = document.createElement("div");
    document.body.appendChild(host);
    root = createRoot(host);
    act(() => {
      root!.render(createElement<Fabric3DProps>(Fabric3D, {}));
    });
    expect(built.opts).toHaveLength(1);
  });

  for (const [n, f] of [
    [300, F300],
    [1000, F1000],
  ] as const) {
    it(`${n}: no single slice overruns by more than one cable's ladder, and slices are many`, { timeout: 600_000 }, () => {
      const job = layoutJob(optsOf(f));
      let slices = 0;
      while (job.step(LAYOUT_SLICE_WORK) === null) slices += 1;
      // Every slice but the last spends at least its budget and less than budget + one indivisible step.
      expect(slices + 1).toBeGreaterThanOrEqual(job.work / (LAYOUT_SLICE_WORK + job.largestStep));
      expect(slices).toBeGreaterThan(10);
      // The largest indivisible step is under a slice, so a slice is at most twice its budget. On these
      // fleets that step is an ordering pass or the embedding (each charged N+E: 820 at 300, 2 738 at
      // 1 000); a cable's whole detour ladder is smaller (~150-900 units). Past N+E = LAYOUT_SLICE_WORK
      // (~1 500 campus nodes) one ordering pass is itself longer than a slice — stated, not hidden.
      expect(job.largestStep, `largest indivisible step ${job.largestStep}`).toBeLessThan(LAYOUT_SLICE_WORK);
      expect(job.result).toEqual(computeLayout(optsOf(f)));
    });
  }

  it("300: the mounting render does not lay the fleet out, and no scene exists until the layout does", { timeout: 600_000 }, async () => {
    useInvestigation.getState().reset();
    host = document.createElement("div");
    document.body.appendChild(host);
    root = createRoot(host);
    act(() => {
      root!.render(createElement<Fabric3DProps>(Fabric3D, { devices: F300.devices, links: F300.links, tiers: F300.tiers }));
    });
    expect(built.opts, "the mounting render laid the whole fleet out: a scene exists after the first commit").toHaveLength(0);
    expect(host.querySelector("canvas")).toBeNull();
    // Let the slices run: each is a task of its own.
    for (let i = 0; i < 400 && built.opts.length === 0; i += 1) await flushTurns(0);
    expect(built.opts).toHaveLength(1);
    const opts = built.opts[0] as SceneOptions;
    expect(opts.layout).toEqual(computeLayout(optsOf(F300)));
  });

  it("an orbit drag is not a hover: the scene's hover events during a press commit nothing", async () => {
    /* MEASURED (2026-09-28, Chromium, Intel iGPU via ANGLE/D3D11, the 300 fleet, dev build, 6 s orbit
       drags with a CPU profile): FabricLabels.tsx was ~3.0-3.7 s inclusive of each 6 s, almost all of
       it React re-rendering every device's label element — once per change of the HOVERED device. The
       stage's own hover path already treats a pointer held down as an orbit ("hover during an orbit
       drag is noise"), but the scene's hover events (interaction.ts, flushed every frame, drag or not)
       reached the same channel through `onEvent`, so on a dense fabric the pointer sweeping across
       chassis mid-orbit re-rendered the label layer frame after frame. One rule for both paths: while
       the stage holds a press, no hover is published. Asserted as COMMITS (React's Profiler): none may
       follow a scene hover while the press is held, and one must before and after it. */
    useInvestigation.getState().reset();
    const { fabric } = await import("../core/data");
    let commits = 0;
    host = document.createElement("div");
    document.body.appendChild(host);
    root = createRoot(host);
    act(() => {
      root!.render(
        createElement(Profiler, { id: "stage", onRender: () => void (commits += 1) }, createElement<Fabric3DProps>(Fabric3D, {})),
      );
    });
    const cb = built.cb[0] as { onEvent: (e: SceneEvent) => void };
    const canvas = host.querySelector<HTMLCanvasElement>("canvas")!;
    const hoverOn = (i: number): void => {
      const d = fabric.devices[i]!;
      act(() => {
        cb.onEvent({ type: "hover", result: { kind: "device", id: d.id, screen: { x: 1, y: 1 } } });
      });
    };
    const press = (type: string): void => {
      act(() => {
        canvas.dispatchEvent(new MouseEvent(type, { bubbles: true, clientX: 10, clientY: 10, button: 0 }));
      });
    };
    let before = commits;
    hoverOn(0);
    expect(commits, "precondition: a scene hover with no press reaches the stage").toBeGreaterThan(before);
    press("pointerdown");
    before = commits;
    for (let i = 1; i < 10; i += 1) hoverOn(i);
    expect(commits - before, "scene hovers during an orbit drag re-rendered the stage").toBe(0);
    press("pointerup");
    before = commits;
    hoverOn(12);
    expect(commits, "hover never came back after the press ended").toBeGreaterThan(before);
  });

  it("swapping to a fabric too large for one slice replaces the scene; no scene is ever handed devices with another fabric's geometry", { timeout: 600_000 }, async () => {
    /* What the stage does while a NEW large fabric is laid out, stated by the component's comments and
       pinned here: the old scene is released in the commit that brings the new inputs (the stage reads
       as "Building the 3-D fabric" meanwhile), and the new scene is BUILT from the new layout once it
       exists. setData — the in-place path — is never called with the new devices and an old layout. */
    useInvestigation.getState().reset();
    const { fabric } = await import("../core/data");
    host = document.createElement("div");
    document.body.appendChild(host);
    root = createRoot(host);
    act(() => {
      root!.render(createElement<Fabric3DProps>(Fabric3D, {}));
    });
    expect(built.opts, "precondition: the sample's scene is built in its mounting commit").toHaveLength(1);
    const sampleLayout = (built.opts[0] as SceneOptions).layout;
    act(() => {
      root!.render(createElement<Fabric3DProps>(Fabric3D, { devices: F300.devices, links: F300.links, tiers: F300.tiers }));
    });
    expect(built.disposed, "the sample's scene outlived the inputs it was drawing").toBe(1);
    expect(host.querySelector("canvas"), "a canvas is still on screen while no layout for the new fabric exists").toBeNull();
    for (let i = 0; i < 400 && built.opts.length < 2; i += 1) await flushTurns(0);
    expect(built.opts).toHaveLength(2);
    const next = built.opts[1] as SceneOptions;
    expect(next.devices).toBe(F300.devices);
    expect(next.layout).toEqual(computeLayout(optsOf(F300)));
    expect(next.layout).not.toBe(sampleLayout);
    // The in-place path never mixed the two: no setData paired the new devices with the old geometry.
    expect(built.setData.filter((c) => c.devices === F300.devices && c.layout === sampleLayout)).toEqual([]);
    expect(fabric.devices.length, "precondition: the swap is to a larger fabric").toBeLessThan(F300.devices.length);
  });
});

/* ── the measuring command refuses a gate it could not judge ───────────────── */

describe("review/synth-fleet.mjs refuses arguments that would make its laboratory gate pass without judging", () => {
  /* `--budget-ms` turns the median into an exit code. A budget that is not a finite positive number
     (NaN compares false with everything, so `median > NaN` never fails), a budget given without
     `--measure` (nothing is timed, exit 0), or a run count that times nothing, each passed the gate
     without a measurement. Each must be refused with exit 2 BEFORE a fleet is generated or written. */
  const run = (args: string[]) =>
    spawnSync(process.execPath, [resolve(process.cwd(), "review", "synth-fleet.mjs"), ...args], {
      cwd: process.cwd(),
      encoding: "utf8",
      timeout: 120_000,
    });
  for (const args of [
    ["--devices", "40", "--measure", "--runs", "1", "--budget-ms", "not-a-number"],
    ["--devices", "40", "--measure", "--runs", "1", "--budget-ms", "0"],
    ["--devices", "40", "--measure", "--runs", "1", "--budget-ms", "-5"],
    ["--devices", "40", "--measure", "--runs", "1", "--budget-ms", "Infinity"],
    ["--devices", "40", "--budget-ms", "300"],
    ["--devices", "40", "--measure", "--runs", "0"],
    ["--devices", "40", "--measure", "--runs", "2.5"],
    ["--devices", "40", "--measure", "--runs", "many"],
  ]) {
    it(`refuses ${args.slice(2).join(" ")}`, { timeout: 120_000 }, () => {
      const r = run(args);
      expect(r.status, `exit ${r.status}; stdout ${r.stdout}; stderr ${r.stderr}`).toBe(2);
      expect(r.stdout, "a fleet was generated before the arguments were judged").not.toContain("wrote ");
      expect(r.stdout).not.toContain("LABORATORY");
    });
  }
});

/* ── the fabric list at fleet scale ───────────────────────────────────────── */

describe("the fabric list stays usable at 300+ devices", () => {
  let root: Root | null = null;
  let host: HTMLElement | null = null;
  const mount = (f: Pick<Fabric, "devices" | "links" | "tiers">): HTMLElement => {
    useInvestigation.getState().reset();
    host = document.createElement("div");
    document.body.appendChild(host);
    root = createRoot(host);
    act(() => {
      root!.render(
        createElement(FabricA11yTree, {
          devices: f.devices,
          links: f.links,
          tiers: f.tiers,
          visible: true,
          onHide: () => {},
          onFocusDevice: () => {},
        }),
      );
    });
    return host;
  };
  afterEach(() => {
    act(() => {
      root?.unmount();
    });
    host?.remove();
    root = null;
    host = null;
  });
  const rows = (h: HTMLElement, kind: string) => [...h.querySelectorAll<HTMLElement>(`[data-testid="fabric3d-tree-${kind}"]`)];

  for (const [n, f] of [
    [300, F300],
    [1000, F1000],
  ] as const) {
    it(`${n}: opens only what fits the budget, and every tier row still states its count`, () => {
      const h = mount(f);
      const tierRows = rows(h, "tier");
      expect(tierRows).toHaveLength(f.tiers.length);
      const shown = rows(h, "device").length;
      expect(shown).toBeGreaterThan(0);
      expect(shown).toBeLessThanOrEqual(TREE_OPEN_DEVICE_BUDGET);
      f.tiers.forEach((t, i) => expect(tierRows[i]!.textContent).toContain(`${t.length} device`));
      const closed = tierRows.filter((r) => r.getAttribute("aria-expanded") === "false");
      expect(closed.length).toBeGreaterThan(0);
      // The collapsed remainder is stated, with its count, and wired to the tree's description.
      const note = h.querySelector<HTMLElement>('[data-testid="fabric3d-tree-collapsed"]')!;
      expect(note.textContent).toContain(`${n - shown} devices are in ${closed.length} collapsed`);
      expect(h.querySelector('[role="tree"]')!.getAttribute("aria-describedby")).toContain(note.id);
      // No link row is built into the DOM until its device is opened.
      expect(rows(h, "link")).toHaveLength(0);
    });
  }

  it("type-ahead finds a device inside a collapsed tier, opens that tier, and moves to it", () => {
    const h = mount(F300);
    const target = F300.tiers.reduce((a, b) => (b.length > a.length ? b : a))[100]!;
    expect(rows(h, "device").some((r) => r.dataset.target === target), "precondition: the target is not listed").toBe(false);
    const tree = h.querySelector<HTMLElement>('[role="tree"]')!;
    act(() => {
      rows(h, "tier")[0]!.focus();
    });
    for (const ch of target) {
      act(() => {
        tree.dispatchEvent(new KeyboardEvent("keydown", { key: ch, bubbles: true, cancelable: true }));
      });
    }
    const row = rows(h, "device").find((r) => r.dataset.target === target);
    expect(row, "the device was not listed after type-ahead").toBeDefined();
    expect(document.activeElement).toBe(row);
    expect(row!.tabIndex).toBe(0);
  });

  it("the reference sample is unchanged: every tier open, every device listed, no collapse note", async () => {
    const { fabric } = await import("../core/data");
    expect(fabric.devices.length, "precondition: the sample fits the open budget").toBeLessThanOrEqual(TREE_OPEN_DEVICE_BUDGET);
    const h = mount(fabric);
    expect(rows(h, "tier").every((r) => r.getAttribute("aria-expanded") === "true")).toBe(true);
    expect(rows(h, "device")).toHaveLength(fabric.devices.length);
    expect(h.querySelector('[data-testid="fabric3d-tree-collapsed"]')).toBeNull();
  });
});
