"""Regenerate engine-collection-completeness.json beside this file FROM THE ENGINE'S OWN PIPELINE.

Run from the repository root with the repository's interpreter (the real offline pipeline, about a minute):

    python atlas-scope/tools/fixtures/engine-collection-completeness.py           (rewrite the fixture)
    python atlas-scope/tools/fixtures/engine-collection-completeness.py --check   (exit 1 unless byte-identical)
    python atlas-scope/tools/fixtures/engine-collection-completeness.py --snapshot-out <path>
                                                    (also write the whole engine snapshot, e.g. for a browser proof)

Why a fixture at all (acceptance B7; atlas-scope/src/app/collection-coverage.b7.test.tsx). The engine's own
authority on how completely each device was collected is `collection_completeness` (cisco_toolkit/analyze.py
`compute_collection_completeness`; its `summary.complete` is the canonical `n_collected`, cisco_toolkit/ssot.py
CANONICAL_FACTS). The tracked sample collects every inventoried device completely, so its block reads
`{complete: 23, partial: 0, not_collected: 0, devices: []}` and a consumer that counts a device RECORD as a
collection agrees with it by construction. This fixture holds the producer's real answer for the two cases the
sample never exercises, produced by the pipeline itself and never restated by hand:

  webapp/sample_data/build_sample.py, run exactly as it runs (its own argv: `--no-collect` over a written
  collection, the pinned collection stamp and registry clock), over the sample collection plus two inventoried
  hosts cloned from access1's platform:
    deadsw  an EMPTY capture folder (inventoried, nothing captured: the engine still writes a device record)
    partsw  only access1's `show version` captured
  and from its snapshot, verbatim: `collection_completeness`, `executive_brief.scale.n_collected`, and the
  device record, cable-map node and health-score row of each added host.

The test patches those rows into the tracked sample and compiles the result with the one compiler, so every
other record is the real sample. Byte-reproducible: the source is recorded as POSIX literals and the file is
written UTF-8 with LF newlines. --check regenerates in memory and compares with the file.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, REPO)
sys.path.insert(0, os.path.join(REPO, "webapp", "sample_data"))

import cisco_toolkit  # noqa: E402

if os.path.dirname(os.path.abspath(cisco_toolkit.__file__)) != os.path.join(REPO, "cisco_toolkit"):
    raise SystemExit("refusing: cisco_toolkit was imported from outside this repository")

import build_sample as bs  # noqa: E402  (the sample's own builder, imported read-only)

SOURCE_REL = "webapp/sample_data/build_sample.py"
TEMPLATE_HOST = "access1"
ADDED = {"deadsw": "an empty capture folder", "partsw": "only show version captured"}

_real_collections = bs.build_collections


def _with_added_hosts():
    cols = _real_collections()
    plat, outputs = cols[TEMPLATE_HOST]
    cols["deadsw"] = (plat, {})
    cols["partsw"] = (plat, {"show version": outputs["show version"]})
    return cols


def _engine_snapshot(scratch_dir):
    bs.build_collections = _with_added_hosts
    try:
        out = os.path.join(scratch_dir, "engine.snapshot.json")
        bs.main(["--out", out])
        with open(out, encoding="utf-8") as fh:
            return json.load(fh), out
    finally:
        bs.build_collections = _real_collections


args = sys.argv[1:]
snapshot_out = args[args.index("--snapshot-out") + 1] if "--snapshot-out" in args else None

import shutil  # noqa: E402
import tempfile  # noqa: E402

scratch = tempfile.mkdtemp(prefix="engine_collection_completeness_")
try:
    snap, written = _engine_snapshot(scratch)
    if snapshot_out is not None:
        shutil.copyfile(written, snapshot_out)
finally:
    shutil.rmtree(scratch, ignore_errors=True)

doc = {
    "about": "The engine's own collection_completeness answer for an empty-capture host and a show-version-only host, "
    "with the records it wrote for them. Generated by atlas-scope/tools/fixtures/engine-collection-completeness.py "
    "(see its docstring); never edit by hand.",
    "recordsFrom": SOURCE_REL,
    "templateHost": TEMPLATE_HOST,
    "added": ADDED,
    "collection_completeness": snap["collection_completeness"],
    "n_collected": snap["executive_brief"]["scale"]["n_collected"],
    "devices": {h: snap["devices"][h] for h in ADDED},
    "cable_map_nodes": [n for n in snap["cable_map"]["nodes"] if n.get("host") in ADDED],
    "health_scores": [r for r in snap["health_scores"] if r.get("switch") in ADDED],
}
text = json.dumps(doc, indent=1, ensure_ascii=False, sort_keys=False) + "\n"
TARGET = os.path.join(HERE, "engine-collection-completeness.json")
if "--check" in args:
    with open(TARGET, "rb") as fh:
        on_disk = fh.read()
    fresh = text.encode("utf-8")
    if on_disk != fresh:
        raise SystemExit(f"engine-collection-completeness.json differs from a regeneration ({len(on_disk)} bytes on disk, {len(fresh)} regenerated)")
    print(f"engine-collection-completeness.json is byte-identical to a regeneration ({len(fresh)} bytes)")
    raise SystemExit(0)
with open(TARGET, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(text)
print(f"collection_completeness.summary = {doc['collection_completeness']['summary']}  n_collected = {doc['n_collected']}")
