"""Regenerate engine-sparse-interfaces.json beside this file FROM THE ENGINE'S OWN FUNCTIONS.

Run from the repository root with the repository's interpreter:

    python atlas-scope/tools/fixtures/engine-sparse-interfaces.py           (rewrite the fixture)
    python atlas-scope/tools/fixtures/engine-sparse-interfaces.py --check   (exit 1 unless byte-identical)

Why a fixture at all (atlas-scope/src/core/compile-validate.test.ts, "the engine's on-disk form"): the
engine writes `<output>.snapshot.json` with its interfaces SPARSIFIED (COLLECT_PARSE_V3_23_0.py
`write_json_file(..., sparsify_interfaces(snap_dict), compact=True)`), and the compiler must compile that
form to the same model as the dense in-memory form. Neither the golden nor the sample carries a single
field the encoder drops, so a sparse copy of either is the identity transform and proves nothing. The
pair below is produced by the producer itself, never restated by hand:

  dense  -- `dataclasses.asdict(cisco_toolkit.model.InterfaceData.from_sparse(rec))` for every interface
            record of tests/golden/snapshot.json. That is exactly how the engine builds its in-memory
            snapshot (cisco_toolkit/html.py: `{port: dataclasses.asdict(d) ...}`), and `from_sparse` is the
            engine's own decode, which restores every field the on-disk encoder omitted to its default.
  sparse -- `cisco_toolkit.html.sparsify_interfaces({"interfaces": dense})["interfaces"]`: the engine's
            on-disk encoder applied to that dense form.

Byte-reproducible on every platform (verifier R3-V2R-5): the source is recorded as the POSIX literal
SOURCE_REL, never an os.path.join (which recorded a backslash path on Windows and a slash path elsewhere),
and the file is written UTF-8 with LF newlines. --check regenerates in memory and compares with the file.
"""
import dataclasses
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, REPO)

from cisco_toolkit.html import sparsify_interfaces  # noqa: E402  (the repository's engine, not an installed copy)
from cisco_toolkit.model import InterfaceData  # noqa: E402

import cisco_toolkit  # noqa: E402

if os.path.dirname(os.path.abspath(cisco_toolkit.__file__)) != os.path.join(REPO, "cisco_toolkit"):
    raise SystemExit("refusing: cisco_toolkit was imported from outside this repository")

SOURCE_REL = "tests/golden/snapshot.json"
with open(os.path.join(REPO, *SOURCE_REL.split("/")), encoding="utf-8") as fh:
    golden = json.load(fh)

dense = {
    host: {port: dataclasses.asdict(InterfaceData.from_sparse(rec)) for port, rec in ports.items()}
    for host, ports in golden["interfaces"].items()
}
sparse = sparsify_interfaces({"interfaces": dense})["interfaces"]

doc = {
    "about": "The engine's dense in-memory interface records and its own on-disk sparse encoding of them. "
    "Generated by atlas-scope/tools/fixtures/engine-sparse-interfaces.py (see its docstring); never edit by hand.",
    "recordsFrom": SOURCE_REL,
    "dense": dense,
    "sparse": sparse,
}
text = json.dumps(doc, indent=1, ensure_ascii=False, sort_keys=False) + "\n"
TARGET = os.path.join(HERE, "engine-sparse-interfaces.json")
if "--check" in sys.argv[1:]:
    with open(TARGET, "rb") as fh:
        on_disk = fh.read()
    fresh = text.encode("utf-8")
    if on_disk != fresh:
        raise SystemExit(f"engine-sparse-interfaces.json differs from a regeneration ({len(on_disk)} bytes on disk, {len(fresh)} regenerated)")
    print(f"engine-sparse-interfaces.json is byte-identical to a regeneration ({len(fresh)} bytes)")
    raise SystemExit(0)
with open(TARGET, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(text)

cells = lambda d: sum(len(r) for ports in d.values() for r in ports.values())  # noqa: E731
print(f"dense {cells(dense)} fields, sparse {cells(sparse)} fields, over {sum(len(p) for p in dense.values())} ports")
