"""Shared high-confidence privacy scan for Atlas compiler and release outputs.

The scanner deliberately reports only rule, path, and line. Matched values are
never retained in a ledger, exception, or generated artifact.
"""

from __future__ import annotations

import re
from typing import Any


FORBIDDEN_CONTENT_RULES = (
    ("private_key_material", re.compile("-----BEGIN " + r"(?:RSA |EC |OPENSSH )?PRIVATE KEY-----")),
    ("aws_access_key", re.compile(r"\b(?:AKIA|ASIA)[0-9A-Z]{16}\b")),
    ("github_access_token", re.compile(r"\bgh[pousr]_[A-Za-z0-9]{36,}\b")),
    ("openai_api_key", re.compile(r"\bsk-(?:proj-)?[A-Za-z0-9_-]{32,}\b")),
    ("slack_access_token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{20,}\b")),
    ("google_api_key", re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b")),
)


def forbidden_content_findings(path: str, text: str) -> list[dict[str, Any]]:
    """Return high-confidence findings without copying the matched value."""

    findings: list[dict[str, Any]] = []
    for rule, pattern in FORBIDDEN_CONTENT_RULES:
        for match in pattern.finditer(text):
            findings.append(
                {
                    "path": path,
                    "line": text.count("\n", 0, match.start()) + 1,
                    "rule": rule,
                }
            )
    return findings


def forbidden_byte_findings(path: str, value: bytes) -> list[dict[str, Any]]:
    """Scan UTF-8-compatible spans in generated bytes, including text archives."""

    return forbidden_content_findings(path, value.decode("utf-8", errors="ignore"))
